### ISSUE TITLE
Create support for a .vpt.yml to enable/disable actions and checks

### ISSUE THREAD

**Issue by Flipez** [voxpupuli/vox-pupuli-tasks#304]
As mentioned in https://github.com/voxpupuli/vox-pupuli-tasks/issues/156 we currently have a list a repositories we ignore. And when we ignore them, we do it completely.

I propose a `.vpt.yml` where we can set the repository to be ignored completely and enable/disable different checks. I imagine it a bit similiar to the `.rubocop.yml`.

As a first iteration I would introduce the ignore flag and a simple flag for each check.

@bastelfreak WDYT?

**Comment by bastelfreak** [comment]
sounds like a good idea to me. we already have a .sync.yml to configure certain options for modulesync, maybe we can extend that with options for vpt.

**Comment by Flipez** [comment]
I have no solid opinion and would stick to whatever you (or someone else) think would fit best in current workflows

**Comment by ekohl** [comment]
One other thing to consider: you should ignore archived repos. I'm not sure if we have any today, but we at least don't manage all. For example, we've dropped puppet-wget. Have you considered using https://github.com/voxpupuli/modulesync_config/blob/master/managed_modules.yml (and possibly https://github.com/voxpupuli/pdksync_config/blob/master/managed_modules.yml) as a source?

**Comment by ekohl** [comment]
I have another good reason this is a bad idea: it breaks modulesync:
```text
Syncing 'puppet-example'
Overriding any local changes to repository in 'modules/voxpupuli/puppet-example'
Creating new branch new-rubocop from master
puppet-example: Error while rendering file: 'vpt'
bundler: failed to load command: msync (/home/ekohl/.gem/ruby/bin/msync)
/home/ekohl/.gem/ruby/gems/modulesync-2.2.0/lib/modulesync/renderer.rb:20:in `read': No such file or directory @ rb_sysopen - ./moduleroot/vpt.erb (Errno::ENOENT)
	from /home/ekohl/.gem/ruby/gems/modulesync-2.2.0/lib/modulesync/renderer.rb:20:in `build'
```
